/**
 * Sample copy for the /dev/app-ui showcase (dev-only page, so literal strings are fine here).
 * Real screens take their strings from the app dictionaries; dates/numbers there go through Intl —
 * the sample values below are pre-formatted so SSR and hydration always agree.
 */
export type Locale = 'he' | 'en';

export type ResponseRow = {
  id: string;
  name: string;
  attending: boolean;
  adults: number;
  kids: number;
  diet: string[];
  bus: string;
  message: string;
  received: string;
  phone: string;
};

export type SectionItem = {
  id: string;
  name: string;
  icon:
    | 'mail'
    | 'image'
    | 'clock'
    | 'heart'
    | 'map-pin'
    | 'list-plus'
    | 'bus'
    | 'sparkles'
    | 'gift'
    | 'message-circle'
    | 'camera'
    | 'users'
    | 'type';
  locked: boolean;
  on: boolean;
};

const he = {
  meta: {
    title: 'רכיבי הממשק של אפליקציית המארחים',
    intro:
      'כל רכיבי הבסיס של אפליקציית המארחים (סעיף 9B.2) בכל המצבים, ושלוש הרכבות שמשחזרות את app.html. הכל מימין לשמאל עם מאפיינים לוגיים בלבד — עברו ל-English כדי לבדוק LTR.',
    nav: { primitives: 'רכיבים', responses: 'אישורי הגעה', share: 'שיתוף', editor: 'עורך' },
    langHe: 'עברית',
    langEn: 'English',
    langLabel: 'שפת התצוגה',
    navLabel: 'ניווט בעמוד',
    home: 'לדף הבית',
    composition: 'הרכבה',
  },
  common: { close: 'סגירה', cancel: 'ביטול', save: 'שמירה', delete: 'מחיקה' },
  button: {
    note: 'primary · secondary · ghost · danger · WhatsApp, בגדלים 32/40/48. האייקון תמיד בצד ההתחלה; אייקונים כיווניים מתהפכים.',
    variants: 'וריאנטים',
    sizes: 'גדלים',
    states: 'מצבים',
    primary: 'פרסום',
    secondary: 'תצוגה מקדימה',
    ghost: 'פתיחה בלשונית חדשה',
    danger: 'מחיקת התשובה',
    whatsapp: 'שליחה בוואטסאפ',
    small: 'הוספה',
    medium: 'שיתוף',
    large: 'יצירת ההזמנה',
    saving: 'שומר…',
    clickToSave: 'לחצו לשמירה',
    disabled: 'לא זמין',
    link: 'קישור (asChild)',
    fullWidth: 'רוחב מלא',
  },
  iconButton: {
    note: '36×36, אייקון muted; ריחוף מוסיף רקע subtle. label חובה (aria-label), tooltip אופציונלי.',
    back: 'חזרה',
    undo: 'ביטול פעולה',
    redo: 'ביצוע חוזר',
    more: 'פעולות נוספות',
    remove: 'מחיקה',
    mute: 'השתקת מוזיקה',
    close: 'סגירה',
    download: 'הורדה',
  },
  inputs: {
    note: '40px, רדיוס 10, מסגרת line; פוקוס = מסגרת ink + טבעת. נתונים בכיוון LTR (אימייל/טלפון/קישור) נשארים צמודים לקצה ההתחלה של הטופס.',
    text: 'שם האירוע',
    textValue: 'החתונה של נועה ואיתי',
    placeholder: 'למשל: בר המצווה של יונתן',
    search: 'חיפוש לפי שם, טלפון או אימייל',
    email: 'אימייל (dir=ltr)',
    phone: 'טלפון (dir=ltr)',
    url: 'קישור (dir=ltr, textAlign=start)',
    invalid: 'שדה עם שגיאה',
    invalidValue: 'noa@',
    invalidError: 'כתובת האימייל לא תקינה — חסר החלק שאחרי @ (למשל gmail.com)',
    disabled: 'שדה מושבת',
    disabledValue: 'נקבע בתבנית',
    select: 'תאריך עברי',
    selectOptions: ['יום (י״ב בסיון תשפ״ז)', 'ערב — "אור ל…" (אור לי״ג בסיון)', 'ללא'],
    textarea: 'הודעה לאורחים',
    textareaValue: 'נשמח לראותכם! פרטי ההגעה וההסעות בהמשך.',
  },
  field: {
    note: 'תווית 13px/600 עם משבצת בצד השני (L10nTabs), מונה 11px בצד הסוף, עזרה 12px ושגיאה עם aria-describedby.',
    eyebrow: 'שורת פתיחה',
    eyebrowValues: { he: 'אנחנו מתחתנים', en: "We're getting married" },
    location: 'שורת מיקום',
    locationValues: { he: 'זכרון יעקב', en: '' },
    title: 'כותרת',
    titleHelp: 'נלקח מ"פרטי האירוע": נועה & איתי',
    titleOptions: { hosts: 'שמות המארחים', free: 'טקסט חופשי' },
    required: 'שם החתן/כלה',
    requiredValue: 'איתי',
    email: 'אימייל לעדכונים',
    emailValue: 'noa@',
    emailError: 'כתובת האימייל לא תקינה — חסר החלק שאחרי @ (למשל gmail.com)',
    help: 'נשלח אליכם עדכון על כל אישור הגעה.',
  },
  l10n: {
    note: 'טאבים זעירים 22px; נקודה כתומה = חסר תרגום. הקלידו באנגלית והנקודה נעלמת.',
    groupLabel: 'שפת השדה',
    missing: 'חסר תרגום',
    he: 'עב',
    en: 'EN',
    heFull: 'עברית',
    enFull: 'English',
    complete: 'שתי השפות מלאות',
    partial: 'אנגלית חסרה',
  },
  segmented: {
    note: 'רצועת subtle, פריטים 28px. radiogroup — החיצים הולכים לפי הסדר החזותי (בעברית ← בוחר את הבא).',
    device: 'מכשיר',
    mobile: 'נייד',
    desktop: 'מחשב',
    previewLang: 'שפת התצוגה',
    filter: 'סינון תשובות',
    all: 'הכל',
    attending: 'מגיעים',
    notAttending: 'לא מגיעים',
    plan: 'תוכנית',
    monthly: 'חודשי',
    yearly: 'שנתי',
    custom: 'מותאם (בקרוב)',
  },
  switch: {
    note: '\u206636×20\u2069; כשהמתג פעיל הידית זזה לקצה הסוף — בעברית שמאלה.',
    showDate: 'הצגת תאריך',
    showDateHelp: 'לועזי + עברי',
    music: 'מוזיקת רקע',
    musicHelp: 'מתנגנת אחרי פתיחת המעטפה',
    disabledOn: 'מושבת (פעיל)',
    disabledOff: 'מושבת (כבוי)',
  },
  badge: {
    note: '22px, 12px/600. וגם Tag לתגיות קטנות בטבלה.',
    draft: 'טיוטה',
    live: 'פורסם',
    warning: 'שינויים שלא פורסמו',
    danger: 'לא מגיעים',
    neutral: '3 שאלות',
    info: 'חדש',
    tags: ['צמחוני', 'כשר למהדרין', 'ללא גלוטן'],
  },
  card: {
    note: 'surface, מסגרת line, רדיוס 12, shadow-sm. CardTitle לכרטיסי פאנל; tone=info לטיפים.',
    panelTitle: 'טקסטים',
    panelBody: 'כרטיס פאנל בעורך: כותרת 13px/700 muted ומתחתיה השדות.',
    tip: 'טיפ: לחיצה על כל טקסט בתצוגה המקדימה קופצת לשדה שלו.',
  },
  kpi: {
    note: 'ערך 30px/700 במספרים טבלאיים; loading שומר על אותו גודל.',
  },
  bars: {
    note: 'המילוי גדל מקצה ההתחלה — בעברית מימין.',
  },
  table: {
    note: 'כותרות על רקע canvas, ריפוד 12px, עמודות מספריות ממורכזות. מצבי טעינה וריק:',
    loading: 'טעינה',
    empty: 'ריק',
    caption: 'אישורי הגעה',
  },
  overlays: {
    note: 'מגירה 480px שנפתחת מקצה הסוף (בעברית משמאל), דיאלוג 560px. Esc או לחיצה ברקע סוגרים.',
    openDrawer: 'פתיחת מגירה',
    openDialog: 'פרסום ההזמנה…',
    drawerTitle: 'הגדרות ההזמנה',
    drawerDescription: 'שינויים נשמרים אוטומטית.',
    drawerBody:
      'המגירה מוצמדת לקצה הסוף של המסך — בעברית לשמאל, באנגלית לימין — ותופסת את כל הרוחב בנייד. התוכן נגלל בתוכה והכותרת והכפתורים נשארים במקום.',
    dialogTitle: 'פרסום ההזמנה',
    dialogDescription: 'בדקו את הכתובת לפני הפרסום. אפשר לעדכן את ההזמנה גם אחרי שהיא באוויר.',
    slugLabel: 'כתובת ההזמנה',
    slugAvailable: 'הכתובת פנויה',
    issuesTitle: 'לפני שמפרסמים',
    issueWarning: "חסר תרגום לאנגלית ב'שורת מיקום'",
    issueError: 'חסר תאריך אחרון לאישור הגעה',
    publish: 'פרסום',
    published: 'ההזמנה פורסמה',
    publishedDescription: 'הקישור מוכן לשיתוף.',
  },
  toast: {
    note: 'למטה במרכז בנייד, למטה בקצה הסוף במחשב. danger עם duration=Infinity נשאר עד פעולה.',
    label: 'התראה',
    viewport: 'התראות ({hotkey})',
    success: 'כל השינויים נשמרו',
    info: 'הקישור הועתק',
    infoDescription: 'אפשר להדביק אותו בכל צ׳אט.',
    danger: 'השינויים לא נשמרו',
    dangerDescription: 'בדקו את החיבור לאינטרנט ונסו שוב.',
    retry: 'ניסיון חוזר',
    retryAlt: 'ניסיון חוזר לשמירה — אפשר גם ללחוץ Ctrl+S',
    showSuccess: 'הצלחה',
    showInfo: 'רגיל',
    showDanger: 'כשל בשמירה (קבוע)',
  },
  skeleton: {
    note: 'שלדים בצורת הממשק הסופי — בלי ספינרים בעמודים מלאים; הפעימה נעצרת ב-reduced motion.',
  },
  empty: {
    note: 'איור 120px, כותרת, שורה אחת וקריאה לפעולה.',
    title: 'עוד אין תשובות — שתפו את ההזמנה',
    description: 'ברגע שהאורחים יאשרו הגעה, התשובות יופיעו כאן.',
    action: 'שיתוף',
  },
  swatch: {
    note: 'עיגול 28px; נבחר = טבעת ink של 2px עם רווח 2px. PaletteDots לכרטיסי הגלריה.',
    sealLabel: 'צבע החותם',
    seal: { bordeaux: 'בורדו', gold: 'זהב', teal: 'כחול ים', navy: 'כחול לילה', sage: 'מרווה', honey: 'דבש' },
    single: 'ColorSwatch בודד',
    templates: [
      {
        id: 'sahar-bordeaux',
        name: 'סהר בורדו',
        cats: 'חתונה · אירוסין · Save the Date',
        palette: { bg: '#FBF8F4', accent: '#731F2E', ink: '#59141F' },
      },
      {
        id: 'caesarea-shore',
        name: 'חוף קיסריה',
        cats: 'חתונה · אירוסין',
        palette: { bg: '#F7F2EA', accent: '#1E5A67', ink: '#173F4A' },
      },
      {
        id: 'honey-meadow',
        name: 'אחו הדבש',
        cats: 'בייבי שאוור · יום הולדת · ברית',
        palette: { bg: '#FFFEF2', accent: '#E8B93C', ink: '#292119' },
      },
    ],
    paletteLabel: 'צבעי התבנית',
  },
  phone: {
    note: 'מסך \u2066390×844\u2069, מסגרת #111 של 11px, רדיוס 52/42. scale מקטין מהמרכז ומפצה בשוליים שליליים.',
    iframeTitle: 'תצוגה מקדימה של דף הבית',
    childrenLabel: 'children',
    iframeLabel: 'src (iframe)',
  },
  tabs: {
    note: 'לשוניות הסרגל: 32px, אייקון + טקסט; הפעילה על רקע subtle.',
    label: 'חלונית העורך',
    sections: 'סקשנים',
    design: 'עיצוב',
    settings: 'הגדרות',
    designBody: 'בחירת פלטה, גופנים וצבע החותם.',
    settingsBody: 'שפות, כתובת ההזמנה ותאריך אחרון לאישור.',
  },
  responses: {
    title: 'אישורי הגעה',
    subtitle: 'נועה & איתי · יום חמישי, 17 ביוני 2027',
    published: 'פורסם',
    share: 'שיתוף',
    export: 'ייצוא ל-Excel',
    kpis: [
      { key: 'attending', label: 'מגיעים', value: '184', sub: '152 מבוגרים · 32 ילדים' },
      { key: 'responses', label: 'תשובות', value: '97', sub: '+12 השבוע' },
      { key: 'declined', label: 'לא מגיעים', value: '14', sub: '14% מהתשובות' },
      { key: 'deadline', label: 'עד הדדליין', value: '9 ימים', sub: '1 ביוני 2027' },
    ],
    dietTitle: 'העדפות תזונה',
    diet: [
      ['ללא העדפות', 121],
      ['צמחוני', 24],
      ['טבעוני', 9],
      ['כשר למהדרין', 14],
      ['ללא גלוטן', 6],
      ['מנת ילדים', 32],
    ] as [string, number][],
    busTitle: 'מצטרפים להסעה?',
    bus: [
      ['לא צריך', 131],
      ['מתל אביב', 38],
      ['מירושלים', 15],
    ] as [string, number][],
    search: 'חיפוש לפי שם, טלפון או אימייל',
    filter: 'סינון',
    columns: {
      name: 'שם',
      status: 'סטטוס',
      adults: 'מבוגרים',
      kids: 'ילדים',
      diet: 'תזונה',
      bus: 'הסעה',
      message: 'הודעה',
      received: 'התקבל',
    },
    attending: 'מגיעים',
    declined: 'לא מגיעים',
    none: '—',
    caption: 'תשובות האורחים — לחצו על שורה לפרטים',
    noMatch: 'אין תשובות שמתאימות לחיפוש',
    noMatchDescription: 'נסו שם אחר או נקו את הסינון.',
    drawer: {
      description: 'התקבל',
      guests: 'מגיעים',
      adults: 'מבוגרים',
      kids: 'ילדים',
      diet: 'תזונה',
      bus: 'הסעה',
      phone: 'טלפון',
      message: 'הודעה לזוג',
      remove: 'מחיקת התשובה',
    },
    rows: [
      {
        id: 'r1',
        name: 'דנה ויואב כהן',
        attending: true,
        adults: 2,
        kids: 1,
        diet: ['צמחוני'],
        bus: 'מתל אביב',
        message: 'מזל טוב! מתרגשים איתכם ♥',
        received: 'לפני שעה',
        phone: '+972 54-123-4567',
      },
      {
        id: 'r2',
        name: 'מיכל לוי',
        attending: true,
        adults: 1,
        kids: 0,
        diet: ['כשר למהדרין'],
        bus: '—',
        message: '',
        received: 'אתמול',
        phone: '+972 52-765-4321',
      },
      {
        id: 'r3',
        name: 'Sarah & Tom Miller',
        attending: true,
        adults: 2,
        kids: 0,
        diet: ['ללא גלוטן'],
        bus: 'מתל אביב',
        message: "Can't wait!",
        received: 'אתמול',
        phone: '+1 415-555-0134',
      },
      {
        id: 'r4',
        name: 'אבי ורונית פרץ',
        attending: false,
        adults: 0,
        kids: 0,
        diet: [],
        bus: '—',
        message: 'נהיה בחו״ל, מאחלים המון אושר',
        received: 'לפני 3 ימים',
        phone: '+972 50-222-3344',
      },
      {
        id: 'r5',
        name: 'עומר בן דוד',
        attending: true,
        adults: 1,
        kids: 0,
        diet: ['טבעוני'],
        bus: 'מירושלים',
        message: '',
        received: 'לפני 4 ימים',
        phone: '+972 53-987-6543',
      },
      {
        id: 'r6',
        name: 'משפחת אזולאי',
        attending: true,
        adults: 2,
        kids: 3,
        diet: ['מנת ילדים', 'צמחוני'],
        bus: 'לא צריך',
        message: 'נתראה!',
        received: 'לפני שבוע',
        phone: '+972 58-444-5566',
      },
    ] as ResponseRow[],
  },
  share: {
    title: 'ההזמנה באוויר 🎉',
    subtitle: 'שתפו את הקישור — כל עדכון עתידי יתעדכן אוטומטית באותו קישור.',
    linkLabel: 'קישור להזמנה',
    link: 'https://yourapp.co.il/i/noa-and-itay',
    copy: 'העתקה',
    copied: 'הקישור הועתק',
    messageLabel: 'הודעה לשליחה',
    message:
      'היי! 💌 אנחנו מתחתנים ונשמח לראותכם.\nכל הפרטים ואישור הגעה בקישור:\nhttps://yourapp.co.il/i/noa-and-itay',
    whatsapp: 'שליחה בוואטסאפ',
    copyMessage: 'העתקת ההודעה',
    messageCopied: 'ההודעה הועתקה',
    previewLabel: 'כך זה ייראה בוואטסאפ',
    waNames: 'נועה & איתי',
    waLine: 'מתחתנים · 17.06.2027',
    waTitle: 'נועה ואיתי מתחתנים',
    waDescription: 'יום חמישי, 17 ביוני 2027 · זכרון יעקב',
    waDomain: 'yourapp.co.il',
    qrLabel: 'קוד QR',
    qrAlt: 'קוד QR לקישור ההזמנה (דוגמה)',
  },
  editor: {
    back: 'חזרה להזמנות',
    docTitle: 'נועה & איתי · חתונה',
    draft: 'טיוטה',
    saved: 'כל השינויים נשמרו',
    undo: 'ביטול פעולה',
    redo: 'ביצוע חוזר',
    preview: 'תצוגה מקדימה',
    publish: 'פרסום',
    addSection: 'הוספת סקשן',
    locked: 'נעול',
    reorder: 'גרירה לשינוי הסדר',
    toggleSection: 'הצגת הסקשן',
    panelTitle: 'פתיחה (Hero)',
    panelSub: 'המסך הראשון אחרי פתיחת המעטפה. הטקסט מופיע מעל הווידאו.',
    background: 'רקע',
    thumbCaption: 'שקיעה בכרם',
    upload: 'העלאת תמונה או וידאו',
    overlay: 'הכהיית רקע',
    liveHint: 'תצוגה חיה',
    replay: 'הפעלת הפתיחה מחדש',
    openTab: 'פתיחה בלשונית חדשה',
    sections: [
      { id: 'cover', name: 'מעטפה ופתיחה', icon: 'mail', locked: true, on: true },
      { id: 'hero', name: 'פתיחה (Hero)', icon: 'image', locked: true, on: true },
      { id: 'countdown', name: 'ספירה לאחור', icon: 'clock', locked: false, on: true },
      { id: 'story', name: 'הסיפור שלנו', icon: 'heart', locked: false, on: true },
      { id: 'venue', name: 'מקום האירוע', icon: 'map-pin', locked: false, on: true },
      { id: 'timeline', name: 'סדר הערב', icon: 'list-plus', locked: false, on: true },
      { id: 'bus', name: 'הסעות', icon: 'bus', locked: false, on: true },
      { id: 'dress', name: 'קוד לבוש', icon: 'sparkles', locked: false, on: true },
      { id: 'gifts', name: 'מתנות', icon: 'gift', locked: false, on: true },
      { id: 'faq', name: 'שאלות נפוצות', icon: 'message-circle', locked: false, on: true },
      { id: 'gallery', name: 'גלריה', icon: 'camera', locked: false, on: false },
      { id: 'rsvp', name: 'אישור הגעה', icon: 'users', locked: false, on: true },
      { id: 'footer', name: 'סיום', icon: 'type', locked: true, on: true },
    ] as SectionItem[],
    mock: {
      eyebrow: 'אנחנו מתחתנים',
      name1: 'נועה',
      amp: '&',
      name2: 'איתי',
      date: 'יום חמישי, 17 ביוני 2027',
      hebrewDate: 'י״ב בסיון תשפ״ז',
      place: 'זכרון יעקב',
    },
  },
};

export type Copy = typeof he;

const en: Copy = {
  meta: {
    title: 'Host app UI primitives',
    intro:
      'Every primitive (§9B.2) in every state, plus three compositions that reproduce app.html. Logical properties only — switch to עברית to check RTL.',
    nav: { primitives: 'Primitives', responses: 'Responses', share: 'Share', editor: 'Editor' },
    langHe: 'עברית',
    langEn: 'English',
    langLabel: 'Display language',
    navLabel: 'On this page',
    home: 'Home',
    composition: 'Composition',
  },
  common: { close: 'Close', cancel: 'Cancel', save: 'Save', delete: 'Delete' },
  button: {
    note: 'primary · secondary · ghost · danger · WhatsApp in 32/40/48. The icon always sits at the inline-start; directional icons mirror.',
    variants: 'Variants',
    sizes: 'Sizes',
    states: 'States',
    primary: 'Publish',
    secondary: 'Preview',
    ghost: 'Open in new tab',
    danger: 'Delete response',
    whatsapp: 'Send on WhatsApp',
    small: 'Add',
    medium: 'Share',
    large: 'Create invitation',
    saving: 'Saving…',
    clickToSave: 'Click to save',
    disabled: 'Unavailable',
    link: 'Link (asChild)',
    fullWidth: 'Full width',
  },
  iconButton: {
    note: '36×36, muted icon; hover adds a subtle background. `label` is required (aria-label), tooltip optional.',
    back: 'Back',
    undo: 'Undo',
    redo: 'Redo',
    more: 'More actions',
    remove: 'Delete',
    mute: 'Mute music',
    close: 'Close',
    download: 'Download',
  },
  inputs: {
    note: '40px, radius 10, line border; focus = ink border + ring. LTR data (email/phone/URL) stays on the form’s start edge.',
    text: 'Event name',
    textValue: "Noa & Itay's wedding",
    placeholder: "e.g. Jonathan's bar mitzvah",
    search: 'Search by name, phone or email',
    email: 'Email (dir=ltr)',
    phone: 'Phone (dir=ltr)',
    url: 'Link (dir=ltr, textAlign=start)',
    invalid: 'Field with an error',
    invalidValue: 'noa@',
    invalidError: 'This email is missing the part after @ (e.g. gmail.com)',
    disabled: 'Disabled field',
    disabledValue: 'Set by the template',
    select: 'Hebrew date',
    selectOptions: ['Day (12 Sivan 5787)', 'Eve — "Or le…" (eve of 13 Sivan)', 'None'],
    textarea: 'Message to guests',
    textareaValue: 'We would love to see you! Directions and shuttles below.',
  },
  field: {
    note: 'Label 13px/600 with a slot on the other side (L10nTabs), 11px counter at the end, 12px help and error wired with aria-describedby.',
    eyebrow: 'Opening line',
    eyebrowValues: { he: 'אנחנו מתחתנים', en: "We're getting married" },
    location: 'Location line',
    locationValues: { he: 'זכרון יעקב', en: '' },
    title: 'Title',
    titleHelp: 'Taken from "Event details": Noa & Itay',
    titleOptions: { hosts: 'Host names', free: 'Free text' },
    required: 'Partner name',
    requiredValue: 'Itay',
    email: 'Email for updates',
    emailValue: 'noa@',
    emailError: 'This email is missing the part after @ (e.g. gmail.com)',
    help: 'We will email you on every RSVP.',
  },
  l10n: {
    note: 'Tiny 22px tabs; amber dot = missing translation. Type in English and the dot goes away.',
    groupLabel: 'Field language',
    missing: 'Missing translation',
    he: 'עב',
    en: 'EN',
    heFull: 'עברית',
    enFull: 'English',
    complete: 'Both languages filled',
    partial: 'English missing',
  },
  segmented: {
    note: 'Subtle track, 28px items. A radiogroup — arrows follow the visual order (ArrowRight picks the next in LTR).',
    device: 'Device',
    mobile: 'Mobile',
    desktop: 'Desktop',
    previewLang: 'Preview language',
    filter: 'Filter responses',
    all: 'All',
    attending: 'Attending',
    notAttending: 'Not attending',
    plan: 'Plan',
    monthly: 'Monthly',
    yearly: 'Yearly',
    custom: 'Custom (soon)',
  },
  switch: {
    note: '36×20; when on, the knob moves to the inline-end — right in English, left in Hebrew.',
    showDate: 'Show date',
    showDateHelp: 'Gregorian + Hebrew',
    music: 'Background music',
    musicHelp: 'Plays after the envelope opens',
    disabledOn: 'Disabled (on)',
    disabledOff: 'Disabled (off)',
  },
  badge: {
    note: '22px, 12px/600. Plus Tag for small table chips.',
    draft: 'Draft',
    live: 'Published',
    warning: 'Unpublished changes',
    danger: 'Not attending',
    neutral: '3 questions',
    info: 'New',
    tags: ['Vegetarian', 'Mehadrin kosher', 'Gluten-free'],
  },
  card: {
    note: 'Surface, line border, radius 12, shadow-sm. CardTitle for panel cards; tone=info for tips.',
    panelTitle: 'Texts',
    panelBody: 'An editor panel card: 13px/700 muted title, fields below.',
    tip: 'Tip: click any text in the preview to jump to its field.',
  },
  kpi: {
    note: '30px/700 tabular value; loading keeps the exact size.',
  },
  bars: {
    note: 'The fill grows from the inline-start — left in English, right in Hebrew.',
  },
  table: {
    note: 'Header on the canvas bg, 12px cell padding, numeric columns centered. Loading and empty states:',
    loading: 'Loading',
    empty: 'Empty',
    caption: 'RSVPs',
  },
  overlays: {
    note: '480px drawer from the inline-end (right in English), 560px dialog. Esc or an overlay click closes.',
    openDrawer: 'Open drawer',
    openDialog: 'Publish invitation…',
    drawerTitle: 'Invitation settings',
    drawerDescription: 'Changes save automatically.',
    drawerBody:
      'The drawer is attached to the inline-end edge — left in Hebrew, right in English — and takes the full width on phones. Its body scrolls while the header and actions stay put.',
    dialogTitle: 'Publish invitation',
    dialogDescription: 'Check the address before publishing. You can keep editing after it is live.',
    slugLabel: 'Invitation address',
    slugAvailable: 'Available',
    issuesTitle: 'Before you publish',
    issueWarning: 'English translation missing in "Location line"',
    issueError: 'RSVP deadline is missing',
    publish: 'Publish',
    published: 'Your invitation is live',
    publishedDescription: 'The link is ready to share.',
  },
  toast: {
    note: 'Bottom-center on phones, bottom inline-end on desktop. A danger toast with duration=Infinity stays until acted on.',
    label: 'Notification',
    viewport: 'Notifications ({hotkey})',
    success: 'All changes saved',
    info: 'Link copied',
    infoDescription: 'Paste it into any chat.',
    danger: "Changes weren't saved",
    dangerDescription: 'Check your connection and try again.',
    retry: 'Try again',
    retryAlt: 'Retry saving — Ctrl+S also works',
    showSuccess: 'Success',
    showInfo: 'Default',
    showDanger: 'Save failed (persistent)',
  },
  skeleton: {
    note: 'Skeletons shaped like the final UI — never spinners on full pages; the pulse stops under reduced motion.',
  },
  empty: {
    note: '120px illustration, title, one line and a call to action.',
    title: 'No responses yet — share your invitation',
    description: 'As soon as guests RSVP, their answers show up here.',
    action: 'Share',
  },
  swatch: {
    note: '28px circle; selected = 2px ink ring with a 2px gap. PaletteDots for gallery cards.',
    sealLabel: 'Seal color',
    seal: {
      bordeaux: 'Bordeaux',
      gold: 'Gold',
      teal: 'Sea blue',
      navy: 'Night blue',
      sage: 'Sage',
      honey: 'Honey',
    },
    single: 'Single ColorSwatch',
    templates: [
      {
        id: 'sahar-bordeaux',
        name: 'Sahar Bordeaux',
        cats: 'Wedding · Engagement · Save the Date',
        palette: { bg: '#FBF8F4', accent: '#731F2E', ink: '#59141F' },
      },
      {
        id: 'caesarea-shore',
        name: 'Caesarea Shore',
        cats: 'Wedding · Engagement',
        palette: { bg: '#F7F2EA', accent: '#1E5A67', ink: '#173F4A' },
      },
      {
        id: 'honey-meadow',
        name: 'Honey Meadow',
        cats: 'Baby shower · Birthday · Brit',
        palette: { bg: '#FFFEF2', accent: '#E8B93C', ink: '#292119' },
      },
    ],
    paletteLabel: 'Template colors',
  },
  phone: {
    note: '390×844 screen, 11px #111 bezel, radius 52/42. `scale` shrinks from the center with negative-margin compensation.',
    iframeTitle: 'Home page preview',
    childrenLabel: 'children',
    iframeLabel: 'src (iframe)',
  },
  tabs: {
    note: 'Rail tabs: 32px, icon + label; the active tab sits on a subtle background.',
    label: 'Editor rail',
    sections: 'Sections',
    design: 'Design',
    settings: 'Settings',
    designBody: 'Pick a palette, fonts and the seal color.',
    settingsBody: 'Languages, invitation address and RSVP deadline.',
  },
  responses: {
    title: 'RSVPs',
    subtitle: 'Noa & Itay · Thursday, June 17, 2027',
    published: 'Published',
    share: 'Share',
    export: 'Export to Excel',
    kpis: [
      { key: 'attending', label: 'Attending', value: '184', sub: '152 adults · 32 kids' },
      { key: 'responses', label: 'Responses', value: '97', sub: '+12 this week' },
      { key: 'declined', label: 'Not attending', value: '14', sub: '14% of responses' },
      { key: 'deadline', label: 'Until deadline', value: '9 days', sub: 'June 1, 2027' },
    ],
    dietTitle: 'Dietary preferences',
    diet: [
      ['No preference', 121],
      ['Vegetarian', 24],
      ['Vegan', 9],
      ['Mehadrin kosher', 14],
      ['Gluten-free', 6],
      ['Kids meal', 32],
    ],
    busTitle: 'Joining the shuttle?',
    bus: [
      ['Not needed', 131],
      ['From Tel Aviv', 38],
      ['From Jerusalem', 15],
    ],
    search: 'Search by name, phone or email',
    filter: 'Filter',
    columns: {
      name: 'Name',
      status: 'Status',
      adults: 'Adults',
      kids: 'Kids',
      diet: 'Diet',
      bus: 'Shuttle',
      message: 'Message',
      received: 'Received',
    },
    attending: 'Attending',
    declined: 'Not attending',
    none: '—',
    caption: 'Guest responses — click a row for details',
    noMatch: 'No responses match your search',
    noMatchDescription: 'Try another name or clear the filter.',
    drawer: {
      description: 'Received',
      guests: 'Attending',
      adults: 'Adults',
      kids: 'Kids',
      diet: 'Diet',
      bus: 'Shuttle',
      phone: 'Phone',
      message: 'Message to the couple',
      remove: 'Delete response',
    },
    rows: [
      {
        id: 'r1',
        name: 'Dana & Yoav Cohen',
        attending: true,
        adults: 2,
        kids: 1,
        diet: ['Vegetarian'],
        bus: 'From Tel Aviv',
        message: 'Mazal tov! So excited for you ♥',
        received: '1 hour ago',
        phone: '+972 54-123-4567',
      },
      {
        id: 'r2',
        name: 'Michal Levi',
        attending: true,
        adults: 1,
        kids: 0,
        diet: ['Mehadrin kosher'],
        bus: '—',
        message: '',
        received: 'Yesterday',
        phone: '+972 52-765-4321',
      },
      {
        id: 'r3',
        name: 'Sarah & Tom Miller',
        attending: true,
        adults: 2,
        kids: 0,
        diet: ['Gluten-free'],
        bus: 'From Tel Aviv',
        message: "Can't wait!",
        received: 'Yesterday',
        phone: '+1 415-555-0134',
      },
      {
        id: 'r4',
        name: 'Avi & Ronit Peretz',
        attending: false,
        adults: 0,
        kids: 0,
        diet: [],
        bus: '—',
        message: "We'll be abroad — wishing you endless joy",
        received: '3 days ago',
        phone: '+972 50-222-3344',
      },
      {
        id: 'r5',
        name: 'Omer Ben David',
        attending: true,
        adults: 1,
        kids: 0,
        diet: ['Vegan'],
        bus: 'From Jerusalem',
        message: '',
        received: '4 days ago',
        phone: '+972 53-987-6543',
      },
      {
        id: 'r6',
        name: 'The Azoulay family',
        attending: true,
        adults: 2,
        kids: 3,
        diet: ['Kids meal', 'Vegetarian'],
        bus: 'Not needed',
        message: 'See you there!',
        received: '1 week ago',
        phone: '+972 58-444-5566',
      },
    ],
  },
  share: {
    title: 'Your invitation is live 🎉',
    subtitle: 'Share the link — future edits update the same link automatically.',
    linkLabel: 'Invitation link',
    link: 'https://yourapp.co.il/i/noa-and-itay',
    copy: 'Copy',
    copied: 'Link copied',
    messageLabel: 'Message to send',
    message:
      "Hi! 💌 We're getting married and would love to see you.\nAll the details and RSVP here:\nhttps://yourapp.co.il/i/noa-and-itay",
    whatsapp: 'Send on WhatsApp',
    copyMessage: 'Copy message',
    messageCopied: 'Message copied',
    previewLabel: 'How it looks on WhatsApp',
    waNames: 'Noa & Itay',
    waLine: 'Getting married · 06.17.2027',
    waTitle: 'Noa and Itay are getting married',
    waDescription: 'Thursday, June 17, 2027 · Zikhron Ya’akov',
    waDomain: 'yourapp.co.il',
    qrLabel: 'QR code',
    qrAlt: 'QR code for the invitation link (sample)',
  },
  editor: {
    back: 'Back to invitations',
    docTitle: 'Noa & Itay · Wedding',
    draft: 'Draft',
    saved: 'All changes saved',
    undo: 'Undo',
    redo: 'Redo',
    preview: 'Preview',
    publish: 'Publish',
    addSection: 'Add section',
    locked: 'Locked',
    reorder: 'Drag to reorder',
    toggleSection: 'Show section',
    panelTitle: 'Opening (Hero)',
    panelSub: 'The first screen after the envelope opens. The text sits over the video.',
    background: 'Background',
    thumbCaption: 'Vineyard sunset',
    upload: 'Upload image or video',
    overlay: 'Background dimming',
    liveHint: 'Live preview',
    replay: 'Replay opening',
    openTab: 'Open in new tab',
    sections: [
      { id: 'cover', name: 'Envelope & opening', icon: 'mail', locked: true, on: true },
      { id: 'hero', name: 'Opening (Hero)', icon: 'image', locked: true, on: true },
      { id: 'countdown', name: 'Countdown', icon: 'clock', locked: false, on: true },
      { id: 'story', name: 'Our story', icon: 'heart', locked: false, on: true },
      { id: 'venue', name: 'Venue', icon: 'map-pin', locked: false, on: true },
      { id: 'timeline', name: 'Schedule', icon: 'list-plus', locked: false, on: true },
      { id: 'bus', name: 'Shuttles', icon: 'bus', locked: false, on: true },
      { id: 'dress', name: 'Dress code', icon: 'sparkles', locked: false, on: true },
      { id: 'gifts', name: 'Gifts', icon: 'gift', locked: false, on: true },
      { id: 'faq', name: 'FAQ', icon: 'message-circle', locked: false, on: true },
      { id: 'gallery', name: 'Gallery', icon: 'camera', locked: false, on: false },
      { id: 'rsvp', name: 'RSVP', icon: 'users', locked: false, on: true },
      { id: 'footer', name: 'Closing', icon: 'type', locked: true, on: true },
    ],
    mock: {
      eyebrow: "We're getting married",
      name1: 'Noa',
      amp: '&',
      name2: 'Itay',
      date: 'Thursday, June 17, 2027',
      hebrewDate: '12 Sivan 5787',
      place: 'Zikhron Ya’akov',
    },
  },
};

export const COPY: Record<Locale, Copy> = { he, en };
