/**
 * Seed SQL (MASTER_PROMPT §5 / §11 P1): upserts every pack template into invitation_templates and
 * publishes the 3 §10 examples plus one demo invitation per template × event type, owned by a
 * non-login demo user. Idempotent; every document is validated against the contracts first.
 *
 *   npm run db:seed > seed.sql                   # then: psql "$DATABASE_URL" -f seed.sql
 *   npm run db:seed -- --only templates          # just the template rows
 *
 * Slugs: fixtures keep theirs (noa-and-itay, …); demos are demo-<template> for the template's first
 * event type and demo-<template>-<event-type> for the others (the gallery's "Live demo" links).
 */
import {
  DEMO_OWNER_ID,
  demoInvitations,
  seedInvitations,
  seedTemplates,
  seedVersion,
} from '../src/features/invitations/templates/seed-data';

export { DEMO_OWNER_ID, demoInvitations };

const DEMO_OWNER_EMAIL = 'demo-owner@invitations.invalid';

const only = process.argv.includes('--only') ? process.argv[process.argv.indexOf('--only') + 1] : 'all';

function json(value: unknown): string {
  const text = JSON.stringify(value);
  if (text.includes('$json$')) throw new Error('unexpected $json$ in seed data');
  return `$json$${text}$json$::jsonb`;
}

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

export function seedSql(): string {
  const lines: string[] = ['-- generated by scripts/seed.ts — do not edit', 'begin;'];
  const templates = seedTemplates();
  for (const { id, manifest, sort } of templates) {
    lines.push(
      `insert into public.invitation_templates (id, manifest, is_active, sort) values (${lit(id)}, ${json(manifest)}, true, ${sort})`,
      `  on conflict (id) do update set manifest = excluded.manifest, sort = excluded.sort;`,
    );
  }
  if (only !== 'templates') {
    // Non-login owner of the demo invitations. Supabase Auth reads these token columns as strings, so
    // they must be '' rather than NULL (NULL there breaks user listing in the dashboard).
    lines.push(
      `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, confirmation_token, recovery_token,`,
      `    email_change_token_new, email_change, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)`,
      `  values ('00000000-0000-0000-0000-000000000000', ${lit(DEMO_OWNER_ID)}, 'authenticated', 'authenticated', ${lit(DEMO_OWNER_EMAIL)},`,
      `    '', '', '', '', '', '{"provider":"email","providers":["email"]}', '{"name":"Demo invitations"}', now(), now())`,
      `  on conflict (id) do nothing;`,
    );
    const invitations = seedInvitations();
    for (const { id, slug, doc } of invitations) {
      lines.push(
        `with d(doc) as (select ${json(doc)})`,
        `insert into public.invitations (id, owner_id, template_id, slug, status, event_type, draft, published, version, published_at)`,
        `  select ${lit(id)}, ${lit(DEMO_OWNER_ID)}, ${lit(doc.templateId)}, ${lit(slug)}, 'published', ${lit(doc.eventType)}, d.doc, d.doc, 1, now() from d`,
        `  on conflict (slug) do update set template_id = excluded.template_id, event_type = excluded.event_type,`,
        `    draft = excluded.draft, published = excluded.published, status = 'published', published_at = now()`,
        `  where public.invitations.owner_id = ${lit(DEMO_OWNER_ID)};`,
        `insert into public.invitation_versions (invitation_id, version, document)`,
        `  select id, version, published from public.invitations where slug = ${lit(slug)} and owner_id = ${lit(DEMO_OWNER_ID)}`,
        `  on conflict (invitation_id, version) do update set document = excluded.document;`,
      );
    }
    // what the app's startup sync compares with (features/invitations/server/seed-sync.ts): up to date
    lines.push(
      `insert into public.app_meta (key, value) values ('seed_version', ${lit(seedVersion(templates, invitations))})`,
      `  on conflict (key) do update set value = excluded.value, updated_at = now();`,
    );
  }
  lines.push('commit;', '');
  return lines.join('\n');
}

if (process.argv[1]?.endsWith('seed.ts')) process.stdout.write(seedSql());
