/**
 * Seed SQL (MASTER_PROMPT §5 / §11 P1): upserts every pack template into invitation_templates and
 * publishes the 3 §10 examples plus one demo invitation per template × event type, owned by a
 * non-login demo user. Idempotent; every document is validated against the contracts first.
 *
 *   npm run db:seed > seed.sql                   # then: psql "$DATABASE_URL" -f seed.sql
 *   npm run db:seed -- --only templates          # just the template rows
 *
 * Slugs: fixtures keep theirs (noa-and-itay, …); demos are demo-<template> for the template's first
 * event type and demo-<template>-<event-type> for the others (the gallery's "Live demo" links).
 */
import { createHash } from 'node:crypto';
import { InvitationDocumentSchema } from '../src/features/invitations/contracts/schemas';
import type { EventType, InvitationDocument } from '../src/features/invitations/contracts/types';
import { FIXTURES, demoDocument } from '../src/features/invitations/templates/demo';
import { TEMPLATES } from '../src/features/invitations/templates/registry';

export const DEMO_OWNER_ID = '00000000-0000-4000-8000-00000000d3e0';
const DEMO_OWNER_EMAIL = 'demo-owner@invitations.invalid';

const only = process.argv.includes('--only') ? process.argv[process.argv.indexOf('--only') + 1] : 'all';

/** Stable id per slug, so re-seeding updates rows in place. */
function idFor(slug: string): string {
  const h = createHash('md5').update(`badook-invitations:${slug}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

function json(value: unknown): string {
  const text = JSON.stringify(value);
  if (text.includes('$json$')) throw new Error('unexpected $json$ in seed data');
  return `$json$${text}$json$::jsonb`;
}

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

export function demoInvitations(): { slug: string; doc: InvitationDocument }[] {
  const out: { slug: string; doc: InvitationDocument }[] = [];
  for (const doc of Object.values(FIXTURES)) out.push({ slug: doc.share.slug, doc: structuredClone(doc) });
  for (const { manifest, defaults } of TEMPLATES.values()) {
    (Object.keys(defaults.defaults) as EventType[]).forEach((type, i) => {
      const slug = i === 0 ? `demo-${manifest.id}` : `demo-${manifest.id}-${type.replace(/_/g, '-')}`;
      const doc = demoDocument(manifest.id, type);
      doc.share.slug = slug;
      out.push({ slug, doc });
    });
  }
  for (const { slug, doc } of out) {
    const parsed = InvitationDocumentSchema.safeParse(doc);
    if (!parsed.success) throw new Error(`seed document ${slug} is invalid: ${parsed.error.message}`);
  }
  return out;
}

export function seedSql(): string {
  const lines: string[] = ['-- generated by scripts/seed.ts — do not edit', 'begin;'];
  [...TEMPLATES.values()].forEach(({ manifest }, sort) => {
    lines.push(
      `insert into public.invitation_templates (id, manifest, is_active, sort) values (${lit(manifest.id)}, ${json(manifest)}, true, ${sort})`,
      `  on conflict (id) do update set manifest = excluded.manifest, sort = excluded.sort;`,
    );
  });
  if (only !== 'templates') {
    lines.push(
      `insert into auth.users (instance_id, id, aud, role, email, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)`,
      `  values ('00000000-0000-0000-0000-000000000000', ${lit(DEMO_OWNER_ID)}, 'authenticated', 'authenticated', ${lit(DEMO_OWNER_EMAIL)},`,
      `    '{"provider":"email","providers":["email"]}', '{"name":"Demo invitations"}', now(), now())`,
      `  on conflict (id) do nothing;`,
    );
    for (const { slug, doc } of demoInvitations()) {
      const id = idFor(slug);
      lines.push(
        `insert into public.invitations (id, owner_id, template_id, slug, status, event_type, draft, published, version, published_at)`,
        `  values (${lit(id)}, ${lit(DEMO_OWNER_ID)}, ${lit(doc.templateId)}, ${lit(slug)}, 'published', ${lit(doc.eventType)}, ${json(doc)}, ${json(doc)}, 1, now())`,
        `  on conflict (slug) do update set template_id = excluded.template_id, event_type = excluded.event_type,`,
        `    draft = excluded.draft, published = excluded.published, status = 'published', published_at = now()`,
        `  where public.invitations.owner_id = ${lit(DEMO_OWNER_ID)};`,
        `insert into public.invitation_versions (invitation_id, version, document)`,
        `  select id, version, published from public.invitations where slug = ${lit(slug)} and owner_id = ${lit(DEMO_OWNER_ID)}`,
        `  on conflict (invitation_id, version) do update set document = excluded.document;`,
      );
    }
  }
  lines.push('commit;', '');
  return lines.join('\n');
}

if (process.argv[1]?.endsWith('seed.ts')) process.stdout.write(seedSql());
